### ISSUE TITLE
Integration with redux-saga

### ISSUE THREAD

**Issue by psachs21** [loggur/provide-router#1]
I've been trying to get a redux saga that listens to the actions that provide-router emits but the events aren't being picked up. I've confirmed that the actions aren't even hitting the middleware so I'm not sure where the break is occurring. Any ideas? I've got an example running [here](https://github.com/influitive/reforge-boilerplate/tree/ps/router-sagas/examples/counters)

It should print something when the action fires but nothing happens.

**Comment by timbur** [comment]
I tried to decipher how it's supposed to work but it's super confusing to me.  Can you explain what all is supposed to be happening here?  https://github.com/influitive/reforge-boilerplate/blob/ps/router-sagas/examples/counters/src/providers/counter1/sagas.js

My only thought so far is to maybe reverse the order of the middleware if you haven't already tried that.  Also, what is this about exactly?  https://github.com/influitive/reforge-boilerplate/blob/ps/router-sagas/examples/counters/src/providers/index.js#L38

**Comment by psachs21** [comment]
Sure. The counter example has two separate counters. You can navigate the counters by clicking on their respective names.

The saga is a dumb saga, all it's doing is listening for LOCATION_CHANGE events and printing out the action with some % characters. The saga works fine with other actions, it's just the ones being dispatched by the provide-router enhancer that doesn't get picked up. 

I tried moving the middleware around with no luck.

As for my root provider, I was just joining all my providers. This could be the wrong way to do it.

**Comment by timbur** [comment]
Oh weird.  I wonder if it has something to do with the way `react-router-redux` dispatches actions, since that's what `provide-router` is using under the hood.  I'll take a closer look at it tomorrow.

**Comment by psachs21** [comment]
Yeah it is weird, I tried some hacking and placed the syncHistoryWithStore in createProviderStore (line 94) which obviously isn't the solution but it does work better. This leads me to believe that we're not syncing the proper store in the enhancer.

**Comment by timbur** [comment]
I noticed in that repo you had both `provide-router` and your original router provider.  I didn't double check to see if maybe you somehow mixed up the 2 anywhere, although from what I saw, it looked like you were only using `provide-router` and just hadn't deleted your original one yet.

**Comment by psachs21** [comment]
That is correct, I should just delete it.

**Comment by psachs21** [comment]
I think the problem lies somewhere between how react-router-redux syncs the history and how we are creating the store. I did notice that during creation, we extend the store created. I am starting to think the listeners added by sync aren't being copied.

**Comment by timbur** [comment]
Yeah that sounds right.  I'll take a closer look now.

**Comment by psachs21** [comment]
Yeah I'll keep poking it myself.

**Comment by timbur** [comment]
I think the issue is either with:

A) The way `react-router-redux`'s middleware and enhancer works versus the way `redux-saga`'s middleware works.  See https://github.com/yelouafi/redux-saga/issues/234#issuecomment-203554955.

B) Try the changes in the upcoming PR, specifically where I've removed the `history` prop from `counters/src/components/index.js` so that it isn't passed to the `Router` component, as `provide-router` will provide its own created `history` to the `Router`.  Based on your 2nd to last comment, I have a feeling this was actually the problem.

**Comment by psachs21** [comment]
I tried your changes suggested in the PR but that didn't change anything (however I will merge the PR when i have second). I think you're right about [this issue](https://github.com/yelouafi/redux-saga/issues/234#issuecomment-203554955). That feels like the explanation... I guess we can't use enhancers for the router. If we don't use an enhancer, we could sync the final store with history but react-redux-provide doesn't currently support that option. What do you think?

**Comment by timbur** [comment]
It should be the same store regardless.  See https://github.com/loggur/provide-router/blob/6fad275bfc13249ff73dcf6ccab44376529e8d48/src/index.js#L41-L50.

Upon further inspection, I just noticed that the problem might be with `react-router-redux`'s middleware.  See https://github.com/reactjs/react-router-redux/blob/2c88667b1716c7bd39060303e3f376b6fa339f17/src/middleware.js.  It intercepts its `CALL_HISTORY_METHOD` action, and if the router middleware is first, the action will never reach any other reducers/middleware (by calling `next(action)`).  So given that you tried reversing the order of the middleware earlier, my guess is there have been multiple problems here - e.g., both A and B in my last post were true.  I'll add another commit to my PR that reverses the order of the middleware.  Hopefully that solves your problem!

Also, just to be sure, actions don't have to come from generator functions for `redux-saga` to use them, right?

**Comment by psachs21** [comment]
Yeah I noticed the interception of CALL_HISTORY_METHOD but I'm not looking for that action, I'm looking for LOCATION_CHANGE. I think you were correct with A, that we have a different enhancer that creates a different dispatch chain that separates the sagas from router actions. If I remove the router enhancer, and manually syncHistoryToStore with the main store (thus removing our only enhancer), everything works as I'd expect it.

Redux-sagas are triggered by any action, whether they're coming from components or other sagas. And that works fine as long as it's not coming from the router middleware/enhancer.

**Comment by timbur** [comment]
Oh I mixed up `LOCATION_CHANGE` with the renamed `UPDATE_LOCATION`.

Regarding the store + history, since you're combining your providers into one, there should only be one store.  So when `provide-router` [enhances the store](https://github.com/loggur/provide-router/blob/6fad275bfc13249ff73dcf6ccab44376529e8d48/src/index.js#L41-L50), it's synchronizing the `history` with that same `store` via `syncHistoryWithStore` which returns a new synchronized `history` object that is then provided to any component with a `history` propType (e.g., `Router`)... so it should all be the same.

How are you testing my PR?  Are you starting from a fresh clone of my particular repo then `npm install && npm start`?

**Comment by psachs21** [comment]
No, I've been just looking at the changes and copying them in where appropriate. I'm in the middle of some other stuff and this is just one of the many things I'm investigating. I'll do a clean install from your repo. Is it working for you? Are you seeing the saga's console log print '%%%%%%' on navigation?

**Comment by psachs21** [comment]
I've merged your PR but the action is still not being picked up by the sagas. Looking at the changes to redux-saga, I think react-redux-provide may need to expose some kind of hook after the store is created anyways. The new version of redux-saga requires that the middleware is called directly with some arguments after the store is created, after the applyMiddlware step.

**Comment by timbur** [comment]
An enhancer should cover that, since you can do whatever you need to the store after its created within the enhancer.

That said, I figured out the problem and I should have paid closer attention to what you were saying earlier, as it has to do with the order the router enhancer and the middleware are applied.  The router enhancer needs to come before the middleware, as `redux`'s `applyMiddleware` function ultimately produces an enhancer.  I don't remember exactly why, but [the middleware enhancer needs to come before any other enhancers in nearly all other scenarios](https://github.com/loggur/react-redux-provide/blob/0c3f50ac3fe30a4bfcdbad0211ee269268ae230f/src/createProviderStore.js#L56-L62) (except replication).  I think maybe it's required for things like the thunk middleware to work properly.  I'll double check at some point.

So there are a few possible solutions for now:

1) Manually create the middleware enhancer and put it after the router enhancer, like this (tested and it works):
```js
// src/providers/index.js

import counter1 from './counter1';
import counter2 from './counter2';
import provideRouter from 'provide-router';
import { browserHistory } from 'react-router';
import { applyMiddleware } from 'redux';

const router = provideRouter(browserHistory);
// export default {
//   counter1,
//   counter2,
//   router
// };

// alternatively, you can make one provider so actions can be seen
// and issued between different providers.

const actions = {
  ...counter1.actions,
  ...counter2.actions,
  ...router.actions
};
const reducers = {
  ...counter1.reducers,
  ...counter2.reducers,
  ...router.reducers
};
const middleware = [
  counter1.middleware,
  router.middleware
];

const enhancer = [
  router.enhancer,
  applyMiddleware(...middleware)
];

// Use this export instead:

export default {
  root: {
    actions,
    reducers,
    enhancer
  }
};
```

2.  I'll need to double check if it will break other things like the thunk middleware, but it may make more sense to put the middleware enhancer last.

3.  Maybe some new special key like `firstEnhancer`?  Not sure how I feel about this but it would certainly make edge cases like this one slightly easier to account for and eliminate the need to manually import/call `applyMiddleware` while also making it more obvious how a provider's store should be initialized.

**Comment by psachs21** [comment]
I was just about to post the same, I had some help from @SeeThruHead to figure it out. Yeah it was the order of things that was messing things up. The API for that one is a little tricky.

**Comment by psachs21** [comment]
Alright, I think I've got everything working. It's a little wonky looking:
```
const middleware = [
  ...counter1.middleware,
  router.middleware
];

const enhancer = [
  router.enhancer,
  applyMiddleware(...middleware)
];

// counter1/index.js
import sagas from './sagas';

const sagaMiddleware = createSagaMiddleware();

const middleware = [
  sagaMiddleware,
  () => { sagaMiddleware.run(sagas); return next => action => next(action); }
];
```

That works.

**Comment by timbur** [comment]
That's strange.  You should have been able to copy/paste that block of code in my previous post and used it on top of my PR and it should have worked, at least with `redux-saga` v0.9.  With v0.10, `sagaMiddleware.run(sagas)` only need to be run once, right?  In which case:

```js
// src/providers/counter1.js

import reducers from './reducers';
import { actions, actionTypes } from './actions';
import localforage from 'redux-replicate-localforage';
import createSagaMiddleware from 'redux-saga';
import sagas from './sagas';

// Replication options can allow easy optimistic updates and state
// persistance. This example uses localstorage to save changes.

const middleware = createSagaMiddleware(sagas);
const replication = {
  replicator: localforage
};

const enhancer = next => (reducer, initialState, enhancer) => {
  const store = next(reducer, initialState, enhancer);

  middleware.run(sagas);

  return store;
};

export default { ...actionTypes, actions, reducers, replication, middleware, enhancer };
```

And then:
```js
// src/providers/index.js

import counter1 from './counter1';
import counter2 from './counter2';
import provideRouter from 'provide-router';
import { browserHistory } from 'react-router';
import { applyMiddleware } from 'redux';

const router = provideRouter(browserHistory);
// export default {
//   counter1,
//   counter2,
//   router
// };

// alternatively, you can make one provider so actions can be seen
// and issued between different providers.

const actions = {
  ...counter1.actions,
  ...counter2.actions,
  ...router.actions
};
const reducers = {
  ...counter1.reducers,
  ...counter2.reducers,
  ...router.reducers
};
const middleware = [
  counter1.middleware,
  router.middleware
];

const enhancer = [
  router.enhancer,
  applyMiddleware(...middleware),
  counter1.enhancer  // or maybe before/right after router.enhancer?
];

// Use this export instead:

export default {
  root: {
    actions,
    reducers,
    enhancer
  }
};
```

Did you try something like that?

**Comment by timbur** [comment]
I will add that all of this is sort of an unorthodox way to do things, but I can't really recommend a better way until I've finished some other things I'm working on.  Although, if this works for you and you're happy with it then... awesome!  😁👍

**Comment by psachs21** [comment]
I tried that and but redux-saga still complains because the counter1.enhancer runs before the saga middleware applies... Might be missing something somewhere...

**Comment by timbur** [comment]
The `counter1.enhancer` is after the `applyMiddleware`:
```js
const enhancer = [
  router.enhancer,
  applyMiddleware(...middleware),
  counter1.enhancer
];
```

Or does `redux`'s `compose` function (used for applying the enhancers) actually reverse the order for some reason ([it uses `Array.prototype.reduceRight`](https://github.com/reactjs/redux/blob/master/src/compose.js) which is extremely confusing/unreadable to me lol).  If that's the case, then perhaps (unintuitively) putting `counter1.enhancer` either first or second in the `enhancer` array will fix it.

And if that doesn't work then I'm kind of at a loss for how to make everything work together cleanly.

**Comment by psachs21** [comment]
I thought the same thing, but even putting the apply middleware before the enhancer has that enhancer run before it actually sets up the saga middleware. 

This simple setup shows what I mean:

```js
const fakeMiddlewares = [
  () => { console.log('middwared!'); return next => action => next(action); },
  () => next => action => next(action)
];

const fakeEnhancers = [
  (next) => (reducer, initialState, enhancer) => {
    const store = next(reducer, initialState, enhancer);
    console.log('Enhance!');
    return store;
  }
];

const enhancer = [
  applyMiddleware(...fakeMiddlewares),
  ...fakeEnhancers
];
```

Regardless of where you put the enhancers, you will always get 'Enhance!' before the middleware gets initialized (and prints 'middlewared!')

**Comment by psachs21** [comment]
This looks like a problem with the new redux-saga middleware API, in that it needs the middleware chain built before you can run sagas. It's a little bit of a bizarre API, IMO. But it means that this hacky way is actually the only way I can make sure it runs after the middleware chain is built (unless you add some API hook to to run something after the store is created)

**Comment by timbur** [comment]
I just tried the code from my previous comment (with `redux-saga@0.10`) and everything seems to work after moving `counter1.enhancer` before `applyMiddleware`.  After actually reading the comments in Redux's [compose.js](https://github.com/reactjs/redux/blob/master/src/compose.js), it's clear to me now why the order of execution is reversed.

At any rate... I'll submit a PR for you to check out.  😄

**Comment by psachs21** [comment]
Huh... I could have sworn I tried that but you seem to be right... My bad.

**Comment by timbur** [comment]
No problem!  Does that solve everything within this particular issue?

**Comment by psachs21** [comment]
Yeah I think it does. Thanks for all your help!

**Comment by psachs21** [comment]
So, late update but for anyone looking at this later, I realize I can use the onReady property to fire off the sagas. That seems to make sure everything is configured properly. Looks something like this:

```js
import createSagaMiddleware from 'redux-saga';
import sagas from './sagas';

const middleware = createSagaMiddleware();

const onReady = () => middleware.run(sagas);

export default {
  ...map,
  middleware,
  onReady
};
```

**Comment by timbur** [comment]
Oh, nice!  I totally forgot about `onReady` and `onInstantiated` since I've only used them in the context of replication.  That's definitely a cleaner approach than the enhancer.  I'm guessing you're using `onReady` instead of `onInstantiated` because you don't want any sagas to be run until after replication has initialized?

**Comment by psachs21** [comment]
Yeah, I shoulda paid more attention to the docs in the first place. This is
the exact api I was looking for.
